USE bractools;

CREATE TABLE IF NOT EXISTS register_sequences (
  yyyymm CHAR(6) PRIMARY KEY,
  last_num INT UNSIGNED NOT NULL DEFAULT 0,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
